Models/Domain/Pipeline.cs
using System.Drawing;

namespace DevOpsWizard.Models.Domain
{
    public class Pipeline
    {
        public int Id { get; set; }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public string FileName { get; set; }
        public byte[] Content { get; set; }

        public string BuildJsonString {get; set;}
        public string ReleaseJsonString { get; set;}
        public bool IsVisible { get; set; }
    }
}

Pages/Pipelines/Add.cshtml.cs
using DevOpsWizard.data;
using DevOpsWizard.Models.Domain;
using DevOpsWizard.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Microsoft.VisualStudio.Services.WebApi.Patch;
using System.IO.Compression;
using System.IO;
using System.Threading.Tasks;
using System.Drawing;

namespace DevOpsWizard.Pages.Pipelines
{
    public class AddModel : PageModel
    {
        private readonly WizardDbContext dbContext;

        private IHostEnvironment Environment;


        public AddModel(WizardDbContext dbContext, IHostEnvironment _environment)
        {
            this.dbContext = dbContext;
            Environment = _environment;
        }
        [BindProperty]
        public AddPipelineViewModel AddPipelineRequest { get; set; }

        [BindProperty]
        public FileViewModel FileUpload { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {

            var pipelineDomainModel = new Pipeline
            {
                BuildJsonString = AddPipelineRequest.BuildJsonString,
                Name = AddPipelineRequest.Name,
                Description = AddPipelineRequest.Description,
                // ImageURL = AddPipelineRequest.ImageURL,

                ReleaseJsonString = AddPipelineRequest.ReleaseJsonString,
                IsVisible = false
                
            };

            if (FileUpload?.FormFile?.Length > 0)
            {
                using (var stream = new FileStream(Path.Combine(Environment.ContentRootPath, "uploadfiles", FileUpload.FormFile.FileName), FileMode.Create))
                {
                    await FileUpload.FormFile.CopyToAsync(stream);
                }
            }
            //save image to database.
            using (var memoryStream = new MemoryStream())
            {
                if (FileUpload.FormFile != null)
                {
                    await FileUpload.FormFile.CopyToAsync(memoryStream);

                    // Upload the file if less than 2 MB
                    if (memoryStream.Length < 2097152)
                    {
                        pipelineDomainModel.FileName = FileUpload.FormFile.FileName;
                        pipelineDomainModel.Content = memoryStream.ToArray();
                    }
                    else
                    {
                        ModelState.AddModelError("File", "The file is too large.");
                    }
                }
            }




            dbContext.Pipelines.Add(pipelineDomainModel);
            await dbContext.SaveChangesAsync();
            //dbContext.SaveChanges();

            ViewData["Message"] = $"{pipelineDomainModel.Name} created successfully!";
            return RedirectToPage("/Pipelines/list");
            //return Ok(new { count = files.Count, size });


        }

    }
}

Pages/Pipelines/Edit.cshtml.cs
using DevOpsWizard.data;
using DevOpsWizard.Models.Domain;
using DevOpsWizard.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.IO;
using System;
using Microsoft.Extensions.Hosting;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace DevOpsWizard.Pages.Pipelines
{
    public class EditModel : PageModel
    {
        private readonly WizardDbContext dbContext;
        private IHostEnvironment Environment;

        [BindProperty]
        public EditPipelineViewModel EditPipelineViewModel { get; set; }
        public EditModel(WizardDbContext dbContext, IHostEnvironment _environment)
        {
            this.dbContext = dbContext;
            Environment = _environment;

        }

        [BindProperty]
        public FileViewModel FileUpload { get; set; }

        public void OnGet(int id)
        {
            var pipeline = dbContext.Pipelines.Find(id);

            if (pipeline != null)
            {
                EditPipelineViewModel = new EditPipelineViewModel()
                {
                    Id = pipeline.Id,
                    BuildJsonString = pipeline.BuildJsonString,
                    Description = pipeline.Description,
                    Name = pipeline.Name,
                    ReleaseJsonString = pipeline.ReleaseJsonString,
                    Content = pipeline.Content,
                    FileName = pipeline.FileName,
                    IsVisible = pipeline.IsVisible
                };
            }
        }

        public async Task<IActionResult> OnPostUpdate(int id)
        {
            if (EditPipelineViewModel != null)
            {
                var existingpipeline = dbContext.Pipelines.Find(id);
                if (existingpipeline != null)
                {
                   // existingpipeline.Id = EditPipelineViewModel.Id;
                    existingpipeline.BuildJsonString = EditPipelineViewModel.BuildJsonString;
                    existingpipeline.Description = EditPipelineViewModel.Description;
                    existingpipeline.Name = EditPipelineViewModel.Name;
                    existingpipeline.ReleaseJsonString = EditPipelineViewModel.ReleaseJsonString;
                    existingpipeline.IsVisible = EditPipelineViewModel.IsVisible;

                    if (FileUpload?.FormFile?.Length > 0)
                    {
                        using (var stream = new FileStream(Path.Combine(Environment.ContentRootPath, "uploadfiles", FileUpload.FormFile.FileName), FileMode.Create))
                        {
                            await FileUpload.FormFile.CopyToAsync(stream);
                        }
                    }
                    //save image to database.
                    using (var memoryStream = new MemoryStream())
                    {
                        if (FileUpload.FormFile != null)
                        {
                            await FileUpload.FormFile.CopyToAsync(memoryStream);

                            // Upload the file if less than 2 MB
                            if (memoryStream.Length < 2097152)
                            {
                                existingpipeline.FileName = FileUpload.FormFile.FileName;
                                existingpipeline.Content = memoryStream.ToArray();
                            }
                            else
                            {
                                ModelState.AddModelError("File", "The file is too large.");
                            }
                        }
                    }


                   // dbContext.Pipelines.Add(pipelineDomainModel);
                    await dbContext.SaveChangesAsync();

                    //dbContext.SaveChanges();


                    ViewData["Message"] = "Pipeline Saved Successfully";
                    return RedirectToPage("/Pipelines/list");
                }
               
            }
            ViewData["Message"] = "Error with Pipeline Data!";
            return Page(); // RedirectToPage("/Pipelines/list");
        }

        public IActionResult OnPostDelete(int id)
        {
            var existingpipeline = dbContext.Pipelines.Find(id);

            if (existingpipeline != null)
            {
                dbContext.Remove(existingpipeline);
                dbContext.SaveChanges();

                return RedirectToPage("/Pipelines/List");
            }

            return Page();
        }

    }
}

Pages/Pipelines/List.cshtml.cs
using DevOpsWizard.data;
using DevOpsWizard.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Linq;

namespace DevOpsWizard.Pages.Pipelines
{
    public class ListModel : PageModel
    {
        private readonly WizardDbContext dbContext;
        public List<Pipeline> Pipelines { get; set; }

        public ListModel(WizardDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public void OnGet()
        {
            Pipelines = dbContext.Pipelines.ToList();


        }
    }
}

Pages/Pipelines/Add.cshtml
@page
@model DevOpsWizard.Pages.Pipelines.AddModel
@{
    var message = ViewData["Message"]?.ToString();
}


<style type="text/css">


    .photo {
        width: 7em;
        height: 9em;
        border: 1px solid rgb(197, 197, 197);
        border-radius: 4px 4px 4px 4px;
        margin-top: 2px;
        float: left;
    }
</style>

<script type="text/javascript">

    
    $(document).ready(function () {
     

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#imagepreview').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#fileupload").change(function () {
            readURL(this);
        });

    });


</script>





<br />
<br />

<form method="post" enctype="multipart/form-data">

    <h1 class="mb-8"> Add Pipeline </h1>

    @if (!string.IsNullOrWhiteSpace(message))
    {
        <div class="alert alert-success" role="alert">
            @message
        </div>
    }

  
    <div class="form-group">
        <div class="row">
            <div class="col-xs-6" style="margin-bottom: 5px">
                <label class="form-label">Name</label>
                <input type="text" class="form-control" asp-for="AddPipelineRequest.Name" />
            </div>
            <div class="col-xs-6" >
            </div>
        </div>
    </div>

        <div class="col-xs-14" style="margin-bottom: 5px">
            <label class="form-label">Description</label>
            <textarea class="form-control" asp-for="AddPipelineRequest.Description" cols="80" rows="5"></textarea>
        </div>

        <div class="col-xs-14" style="margin-bottom: 5px">
            <label class="form-label">BuildJsonString</label>
            <textarea class="form-control" asp-for="AddPipelineRequest.BuildJsonString" cols="80" rows="5"></textarea>
        </div>

        <div style="margin-bottom: 5px">
            <label class="form-label">ReleaseJsonString</label>
            <textarea class="form-control" asp-for="AddPipelineRequest.ReleaseJsonString" cols="80" rows="5"></textarea>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="FileUpload.FormFile"  class="control-label">
                        Icon
                    </label>
                    <input id="fileupload" asp-for="FileUpload.FormFile" class="form-control" type="file" />
                    <img id="imagepreview" class="photo" ImageUrl="img/user-5.png" style="height: 100px; width: 100px;" />
                    <span asp-validation-for="FileUpload.FormFile" class="text-danger"></span>
                </div>
            </div>
        </div>

    <br />

    <button type="submit" class="btn btn-primary">Save</button>

</form>

Pages/Pipelines/Edit.cshtml
@page "{id:int}"
@model DevOpsWizard.Pages.Pipelines.EditModel
@{
    var message = ViewData["Message"]?.ToString();
}

<style type="text/css">


    .photo {
        width: 7em;
        height: 9em;
        border: 1px solid rgb(197, 197, 197);
        border-radius: 4px 4px 4px 4px;
        margin-top: 2px;
        float: left;
    }
</style>

<script type="text/javascript">


    $(document).ready(function () {

        readURL("#fileupload");

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#imagepreview').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#fileupload").change(function () {
            readURL(this);
        });

    });


</script>

<br />
<br />

<form method="post" enctype="multipart/form-data">

 


    <h1 class="mb-3">Edit Pipeline</h1>


    @if (!string.IsNullOrWhiteSpace(message))
    {
        <div class="alert alert-success" role="alert">
            @message
        </div>
    }


    <div class="form-group">
        <div class="row">
            <div class="col-xs-6" style="margin-bottom: 5px">
                <label class="form-label">Name</label>
                <input type="text" class="form-control" asp-for="EditPipelineViewModel.Name" />
            </div>
            <div class="col-xs-6">
            </div>
        </div>
    </div>

    <div class="col-xs-14" style="margin-bottom: 5px">
        <label class="form-label">Description</label>
        <textarea class="form-control" asp-for="EditPipelineViewModel.Description" cols="80" rows="5"></textarea>
    </div>

    <div class="col-xs-14" style="margin-bottom: 5px">
        <label class="form-label">BuildJsonString</label>
        <textarea class="form-control" asp-for="EditPipelineViewModel.BuildJsonString" cols="80" rows="5"></textarea>
    </div>

    <div style="margin-bottom: 5px">
        <label class="form-label">ReleaseJsonString</label>
        <textarea class="form-control" asp-for="EditPipelineViewModel.ReleaseJsonString" cols="80" rows="5"></textarea>
    </div>
@*
    <div style="margin-bottom: 5px">
        <label class="form-label form-check-label">Visible?</label>
        <input class="form-control form-check-input" asp-for="EditPipelineViewModel.IsVisible"></input>
    </div>*@

    <div style="margin-bottom: 5px" > @* class="form-check">*@
        <label class="form-check-label" for="flexCheckChecked" style="margin-right: 5px">
            Visible: 
        </label>
        <input class="form-check-input" type="checkbox" asp-for="EditPipelineViewModel.IsVisible">
    </div>

    <div class="row">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FileUpload.FormFile" class="control-label">
                    Icon
                </label>
                <input id="fileupload" asp-for="FileUpload.FormFile" class="form-control" type="file" />

                @{

                    if (Model.EditPipelineViewModel.Content != null)
                    {
                        var base64 = Convert.ToBase64String(Model.EditPipelineViewModel.Content);
                        var userImage = String.Format("data:image/gif;base64,{0}", base64);
                        <img id="imagepreview" src="@userImage" class="photo" style="height: 100px; width: 100px;" />
                    }
                    else
                    {
                        <img id="imagepreview" class="photo" ImageUrl="img/user-5.png" style="height: 100px; width: 100px;" />
                    }
                }
                <span asp-validation-for="FileUpload.FormFile" class="text-danger"></span>
            </div>
        </div>
    </div>

    <br />
    <div class="mb-3 d-flex ">
        <button type="submit" class="btn btn-primary " asp-page-handler="Update">Save</button>
        <button type="submit" class="btn btn-danger" asp-page-handler="Delete">Delete</button>
    </div>

</form>

Pages/Pipelines/List.cshtml
@page
@model DevOpsWizard.Pages.Pipelines.ListModel
@{
}
<style type="text/css">
    thead, tbody {
        display: block;
    }
    tbody {
        height: 600px;       /* Just for the demo          */
        overflow-y: auto;    /* Trigger vertical scroll    */
          /* Hide the horizontal scroll */
    }

 

    /*tbody td, thead th {*/
   /* tbody td

    {
         width: 5%; 
         height: 100px;
         max-height: 100px;
         
    }*/

    thead th {
        width: 160px;  /* 23.5%; */

    }

    table {
        table-layout: fixed;
        width: 100%;
    }

    td {
        width: 5%;
        height: 100px;
    }


    


</style>


<br />
<br />
<h1 class="ab-3"> Pipelines List</h1>

@if (Model.Pipelines != null && Model.Pipelines.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Build String</th>
                <th>Release String</th>
                <th>Picture</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var pipeline in Model.Pipelines)
            {
                <tr style="height: 100px">
                    <td>
                        @pipeline.Name
                    </td>
                    <td>@pipeline.Description</td>
                    <td>@pipeline.BuildJsonString</td>
                    <td>
                    <td>
                        <div style="height:  50px; overflow: hidden;">
                            @pipeline.ReleaseJsonString
                        </div>
                    </td>
                    <td>
                        @{
                            if (pipeline.Content != null)
                            {
                                var base64 = Convert.ToBase64String(pipeline.Content);
                                var userImage = String.Format("data:image/gif;base64,{0}", base64);
                                <img src="@userImage" alt="User Image" style="height: 100px; width: 100px;">
                            }
                            else
                            {
                                <img src="~/images/none.jfif" alt="User Image" style="height: 100px; width: 100px;">              
                            }
                        }
                    </td>
                    <td>
                        <a href="/Pipelines/Edit/@pipeline.Id" class="btn  btn-success  ">Edit</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p> No Pipelines found</p>
}